on:
  schedule:
  - cron: '*/2 * * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@Kazanami-patch-1
    - name: Excavate
      uses: Ash258/Scoop-GithubActions@stable
      env:
        GITH_EMAIL: ${{ secrets.DUMMY_ADDRESS }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
    - name: The job has succeeded
      if: ${{ success() }} 
      run: echo "Generating README.md ..."
